### ISSUE TITLE
 Ração pra cachorro

### ISSUE THREAD

**Issue by Isaias-felix-2001** [ifroariquemes/42#55]

**Comment by natanaelsimoes** [comment]
Que post é esse mano????

**Comment by Isaias-felix-2001** [comment]
É do Antônio, ele pediu pra subir o assunto pra ele aí ele tá fzd a matéria
a respeito

Em ter, 12 de nov de 2019 08:46, Natanael Augusto Viana Simões <
notifications@github.com> escreveu:
